name: geoflutterfire
description: GeoFlutterFire is an open-source library that allows you to store and query firestore documents based on their geographic location.
version: 3.0.8

environment:
  sdk: ^3.5.3
  # flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.4.2
  flutter_lints: ^5.0.0
  rxdart: ^0.28.0
  # rxdart: ^0.27.3
  # flutter_lints: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
